# -*- coding: utf-8 -*-
"""Fase2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Crvr9dCQ9StNQbk5i4klxCRByifR0Kde

Crie um algoritmo em Python que peça 2 números e imprima o maior deles.
"""

# INSIRA SEU CÓDIGO AQUI
while True:
  try:
    i = 0
    algarismos = input("Digite quantos números quer inserir, se quiser encerrar digite fim: ")
    lista = []
    while i < int(algarismos):
      num = float(input("Insira o número: "))
      i += 1
      lista.append(num)
    lista_nova = sorted(lista)
    print(f"O maior número é {lista_nova[len(lista_nova)-1]}")
    break
  except ValueError:
    if algarismos == "fim":
      print("Seção encerrada.")
      break
    else:
      print("A quantidade de números a inserir deve ser um número inteiro! Tente novamente.")

"""Crie um algoritmo em Python que peça um valor e mostre na tela se o valor é positivo ou negativo."""

# INSIRA SEU CÓDIGO AQUI
import pandas as pd

while True:
  try:
    i = 0
    vazia = []
    classificacao = []
    quantos = input("Quantos números quer inserir? ")
    while i < int(quantos):
      numero = float(input("Digite o número:"))
      vazia.append(numero)
      i += 1
    for i in vazia:
      if i < 0:
        classificacao.append("Negativo")
      else:
        classificacao.append("Positivo")
    d = {"Classificação":classificacao,"Números digitados":vazia}
    df = pd.DataFrame(d)
    print(df)
    break
  except ValueError:
    if quantos == "fim" or quantos == "Fim" or quantos == "FIM":
      print("Seção encerrada!")
      break
    else:
      print("Valor não inteiro, tente novamente!")

"""Crie um algoritmo em Python que verifique se uma letra digitada é vogal ou consoante."""

# INSIRA SEU CÓDIGO AQUI
while True:
  try:
    palavra = str(input("Escreva uma palavra: "))
    for i in palavra:
      if i in "aeiou" or i in "AEIOU":
        print("É uma vogal")
      else:
        print("É uma consoante")
    break
  except ValueError:
    print("Algo inesperado aconteceu! Digite novamente.")
    if palavra == "fim":
      print("Seção encerrada!")
      break

"""Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e apresentar:
* "Aprovado", se a média alcançada for maior ou igual a sete;
* "Reprovado", se a média for menor do que sete;
* "Aprovado com Distinção", se a média for igual a 10.
"""

# INSIRA SEU CÓDIGO AQUI
while True:
  try:
    i = 0
    soma = 0
    qtd = int(input("Quantas notas quer digitar?"))
    while i < qtd:
      notas = float(input("Escreva a nota do aluno: "))
      soma = soma + notas
      i = i + 1
    media = soma/qtd
    if media < 7:
      print(f"Aluno reprovado! Média {media}")
    elif media >= 7 and media < 10:
      print(f"Aluno aprovado! Média {media}")
    elif media == 10:
      print(f"Aluno aprovado com distinção! Média {media}")
    break
  except ValueError:
    print("Algo inexperado aconteceu, tente novamente!")
  except ZeroDivisionError:
    print("Quantidade deve ser maior do que zero.")

"""Crie um algoritmo em Python que leia três números e mostre o maior deles."""

# INSIRA SEU CÓDIGO AQUI
while True:
  try:
    i = 0
    lista = []
    qtd = int(input("Quantos numeros quer digitar?"))
    while i < qtd:
      num = float(input("Escreva um numero: "))
      lista.append(num)
      i = i + 1
    print(f"O maior numero é {sorted(lista)[len(lista)-1]}")
    break
  except ValueError:
    print("Algo inexperado aconteceu")

"""Crie um algoritmo em Python que leia três números e mostre o maior e o menor deles."""

# INSIRA SEU CÓDIGO AQUI
while True:
  try:
    i = 0
    lista = []
    qtd = int(input("Quantos numeros quer digitar?"))
    while i < qtd:
      num = float(input("Escreva um numero: "))
      lista.append(num)
      i = i + 1
    print(f"O menor numero é {sorted(lista)[0]}")
    break
  except ValueError:
    print("Algo inexperado aconteceu")

"""Faça um programa que pergunte o preço de 5 produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato."""

# INSIRA SEU CÓDIGO AQUI
dic = {"Sabão":6.90, "Bolacha":1.20, "Detergente":1.56, "Kilo da laranja":2.00,"Garrafa de água 500ml":3.50, "Carne":19.90,"Iogurte":5.60, "Shampoo":10.00}
key_concate = ""
lista = []
for key in dic.keys():
  lista.append(key)
for j in lista[0:len(lista)-2]:
  key_concate = key_concate +", "+j
print(f"No nosso mercadinho temos{key_concate} e {lista[len(lista)-1]}")
try:
  preços = []
  i = 0
  saberes = []
  while i < 5:
    saber = str(input("Qual destes você ques saber o preço? ----- R: "))
    if saber in lista:
      saberes.append(saber)
      preços.append(dic[saber])
      i = i + 1
    else:
      print("Esta mercadoria não tem no nosso mercado")
  print(f"O produto mais barato é {sorted(preços)[0]}")
except ValueError:
  print("Produto digitado erroneamente.")
else:
  print("Esta mercadoria não tem no nosso mercado")

"""Crie um algoritmo em Python que leia três números e mostre-os em ordem decrescente."""

# INSIRA SEU CÓDIGO AQUI
while True:
  try:
    i = 0
    lista = []
    qtd = int(input("Quantos numeros quer digitar?"))
    while i < qtd:
      num = float(input("Escreva um numero: "))
      lista.append(num)
      i = i + 1
    print(f"Em ordem decrescente é {sorted(lista, reverse = True)}")
    break
  except ValueError:
    print("Algo inexperado aconteceu")

"""As Organizações Mendéz resolveram dar um aumento de salário aos seus colaboradores e lhe contraram para desenvolver o programa que calculará os reajustes em Python. Faça um programa que receba o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:

* salários entre 680,00 e 800,00 : aumento de 15%<br>
* salários entre 800,00 e 2500,00 : aumento de 10%<br>
* salários de 2500,00 em diante : aumento de 5% após o aumento ser realizado.

Informe na tela:
* o salário antes do reajuste;
* o percentual de aumento aplicado;
* o valor do aumento;
* o novo salário, após o aumento.
"""

# INSIRA SEU CÓDIGO AQUI
while True:
  try:
    salario_antes = input("Digite o seu salário: ")
    if 680 <= float(salario_antes) < 800:
      salario_novo = float(salario_antes)*1.15
      print(f"O salário antes do reajuste era R${salario_antes:.2f}")
      print("O percentual de desconto foi de 15%")
      print(f"O valor do aumento foi {salario_novo:.2f}")
      
    elif 800 <= float(salario_antes) < 2500:
      salario_novo = float(salario_antes)*1.1
      print(f"O salário antes do reajuste era R${salario_antes:.2f}")
      print("O percentual de desconto foi de 10%")
      print(f"O valor do aumento foi R${float(salario_antes)*0.10:.2f}")
      print(f"O salário atual é {salario_novo:.2f}")
      
    elif float(salario_antes) >= 2500:
      salario_novo = float(salario_antes)*1.05
      print(f"O salário antes do reajuste era R${salario_antes:.2f}")
      print("O percentual de desconto foi de 5%")
      print(f"O valor do aumento foi R${float(salario_antes)*0.05:.2f}")
      print(f"O salário atual é {salario_novo:.2f}")
    else:
      print("Este valor não possui reajuste.")
  except ValueError:
    print("Algo inexperado aconteceu! O programa será fechado.")
    break